# Generated by Django 2.2.14 on 2020-09-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_signatario_contrato',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
