# Generated by Django 2.2.14 on 2020-10-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_id_signatario_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto_cnh',
            field=models.ImageField(null=True, upload_to='data/fotos_cnh'),
        ),
    ]
