# Generated by Django 3.0 on 2020-04-07 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('charge_id', models.CharField(max_length=10, null=True)),
                ('dt_hr_inclusao', models.DateTimeField(auto_now_add=True)),
                ('ult_atualizacao', models.DateTimeField(auto_now=True)),
                ('aceito', models.BooleanField(default=False)),
                ('url_pdf', models.CharField(max_length=200, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('produtos_contratados', models.ManyToManyField(to='produto.Produto')),
            ],
        ),
    ]
