# Generated by Django 2.2.14 on 2020-10-10 18:27

from django.db import migrations, models
import django.db.models.deletion
import gerenciadorlog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_cliente_id_signatario_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('placa', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('modelo', models.CharField(max_length=20, null=True)),
                ('marca', models.CharField(max_length=20, null=True)),
                ('ano', models.CharField(max_length=20, null=True)),
                ('apelido', models.CharField(max_length=20, null=True)),
                ('foto_doc', models.ImageField(upload_to='fotos_docs_veiculos')),
                ('dt_hr_inclusao', models.DateTimeField(auto_now_add=True)),
                ('ult_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
            bases=(models.Model, gerenciadorlog.models.GerenciadorLog),
        ),
    ]
